/**
 * This Source Code is based on the original bootstrap.js generated by the
 * add-on sdk which is subject to the terms of the Mozilla Public License, v.
 * 2.0. You can obtain a copy of this license at http://mozilla.org/MPL/2.0/.
 */

"use strict";

const { utils: Cu } = Components;
const rootURI = __SCRIPT_URI_SPEC__.replace("bootstrap.js", "");
const COMMONJS_URI = "resource://gre/modules/commonjs";
const { require } = Cu.import(COMMONJS_URI + "/toolkit/require.js", {});
const { Bootstrap } = require(COMMONJS_URI + "/sdk/addon/bootstrap.js");

const { MigrationOverride } = require(rootURI + "lib/migrationoverride");
MigrationOverride();

var { startup, shutdown, install, uninstall } = new Bootstrap(rootURI);
